services:
  db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80

  redis:
    image: redis:8.2-alpine

  mailpit:
    image: "axllent/mailpit:latest"
    command: --smtp-auth-allow-insecure
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"

  app:
    depends_on:
      - db
      - pgadmin
    build:
      context: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - ${APP_PORT:-5000}:5000
    environment:
      GOOGLE_OAUTH2_KEY: ${GOOGLE_OAUTH2_KEY}
      GOOGLE_OAUTH2_SECRET: ${GOOGLE_OAUTH2_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}

  worker:
    depends_on:
      - redis
      - mailpit
      - app
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A ecommerce_test worker -l info
    environment:
      GOOGLE_OAUTH2_KEY: ${GOOGLE_OAUTH2_KEY}
      GOOGLE_OAUTH2_SECRET: ${GOOGLE_OAUTH2_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      REDIS_URL: ${REDIS_URL}

volumes:
  postgres:
  pgadmin:
