# Generated by Django 5.2.5 on 2025-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_item_quantity_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('D', 'Cancelled')], default='P', max_length=1),
        ),
    ]
